theme = "mikeyc"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://mcornish.github.io/"
languageCode = "en-us"
[params]
  title = "Mike Cornish"
  description = "Web developer/designer Mike Cornish's portfolio"
